# Generated by Django 5.2.8 on 2025-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_language_skill_profile_profilelanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelanguage',
            name='proficiency',
            field=models.CharField(choices=[('beg', 'Beginner'), ('inter', 'Intermediate'), ('expert', 'Expert')], default='beg', max_length=10),
        ),
    ]
